import { ClerkProvider, RedirectToSignIn } from "@clerk/nextjs";
import { Metadata } from "next";
import "./globals.css";
// import CommonLayout from "@/components/CommonLayout";
import Authorizer from "@/components/auth/Authorizer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          {/* Conditionally render layout based on the route */}
          <Authorizer>{children}</Authorizer>
        </body>
      </html>
    </ClerkProvider>
  );
}
