import type { Metadata } from "next";
import "./globals.css";
import CommonLayout from "@/components/CommonLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={` antialiased `}
        >
          <CommonLayout>{children}</CommonLayout>
        </body>
      </html>
  );
}
